version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    container_name: node-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/usr/src/app/logs  # Optional: for log files 